//
//  IconCollection.swift
//  FolderStudio
//

import SwiftUI

struct IconCollection: Identifiable, Hashable {
    let id: String
    let name: String
    let description: String
    let accentColorHex: String
    let iconName: String
    var badge: String? = nil
    var isFeatured: Bool = false
    var categoryTag: String = "Curated"
    var author: String = "FolderStudio"
    var priceText: String = "Free"
    let designs: [IconDesign]
    
    var iconCount: Int {
        designs.count
    }
}

struct CollectionCatalog {
    static let allCollections: [IconCollection] = [
        // 1. Pastel Colors
        IconCollection(
            id: "pastel_colors",
            name: "Pastel Colors",
            description: "Soft, gentle hues that bring a calming warmth to your desktop.",
            accentColorHex: "#F472B6",
            iconName: "paintpalette.fill",
            badge: "TRENDING 🌸",
            isFeatured: false,
            categoryTag: "Aesthetic",
            author: "FolderStudio Official",
            priceText: "Free",
            designs: [
                IconDesign(
                    name: "Mint Fresh",
                    folderStyle: .softPastel,
                    primaryColorHex: "#34D399",
                    secondaryColorHex: "#A7F3D0",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "leaf.fill",
                    symbolColorHex: "#065F46",
                    symbolScale: 0.48,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Lavender Bliss",
                    folderStyle: .softPastel,
                    primaryColorHex: "#C084FC",
                    secondaryColorHex: "#E9D5FF",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "sparkles",
                    symbolColorHex: "#581C87",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Peach Sunrise",
                    folderStyle: .softPastel,
                    primaryColorHex: "#FB923C",
                    secondaryColorHex: "#FED7AA",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "sun.max.fill",
                    symbolColorHex: "#9A3412",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Sky Cotton",
                    folderStyle: .softPastel,
                    primaryColorHex: "#38BDF8",
                    secondaryColorHex: "#BAE6FD",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "cloud.fill",
                    symbolColorHex: "#075985",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Rose Quartz",
                    folderStyle: .softPastel,
                    primaryColorHex: "#F472B6",
                    secondaryColorHex: "#FCE7F3",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "heart.fill",
                    symbolColorHex: "#9D174D",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Buttercup",
                    folderStyle: .softPastel,
                    primaryColorHex: "#FBBF24",
                    secondaryColorHex: "#FEF3C7",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "star.fill",
                    symbolColorHex: "#92400E",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Lilac Whisper",
                    folderStyle: .softPastel,
                    primaryColorHex: "#A78BFA",
                    secondaryColorHex: "#EDE9FE",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "moon.fill",
                    symbolColorHex: "#4C1D95",
                    symbolScale: 0.48,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Sage Field",
                    folderStyle: .softPastel,
                    primaryColorHex: "#6EE7B7",
                    secondaryColorHex: "#D1FAE5",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "drop.fill",
                    symbolColorHex: "#065F46",
                    symbolScale: 0.48,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                )
            ]
        ),
        
        // 2. Developer Essentials
        IconCollection(
            id: "developer_essentials",
            name: "Developer Essentials",
            description: "Distinct icons for repositories, CLI tools, databases, and microservices.",
            accentColorHex: "#3B82F6",
            iconName: "curlybraces",
            badge: "STAFF PICK 💻",
            isFeatured: true,
            categoryTag: "Developer & Tech",
            author: "FolderStudio Official",
            priceText: "Free",
            designs: [
                IconDesign(
                    name: "Terminal Core",
                    folderStyle: .dark,
                    primaryColorHex: "#0F172A",
                    secondaryColorHex: "#1E293B",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "terminal.fill",
                    symbolColorHex: "#34D399",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .roundedRect,
                    badgeColorHex: "#059669",
                    badgeOpacity: 0.20
                ),
                IconDesign(
                    name: "Git Repository",
                    folderStyle: .minimal,
                    primaryColorHex: "#F97316",
                    secondaryColorHex: "#EA580C",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "arrow.triangle.branch",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#000000",
                    badgeOpacity: 0.25
                ),
                IconDesign(
                    name: "Code Source",
                    folderStyle: .neon,
                    primaryColorHex: "#6366F1",
                    secondaryColorHex: "#A855F7",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "chevron.left.forwardslash.chevron.right",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.54,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Cloud Backend",
                    folderStyle: .glass,
                    primaryColorHex: "#0284C7",
                    secondaryColorHex: "#38BDF8",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "externaldrive.fill.badge.icloud",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Database Storage",
                    folderStyle: .minimal,
                    primaryColorHex: "#0D9488",
                    secondaryColorHex: "#14B8A6",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "server.rack",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .squircle,
                    badgeColorHex: "#042F2E",
                    badgeOpacity: 0.25
                ),
                IconDesign(
                    name: "Package Bundle",
                    folderStyle: .classic,
                    primaryColorHex: "#D97706",
                    secondaryColorHex: "#B45309",
                    isGradient: false,
                    overlayType: .symbol,
                    symbolName: "shippingbox.fill",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Bug Tracker",
                    folderStyle: .dark,
                    primaryColorHex: "#7F1D1D",
                    secondaryColorHex: "#450A0A",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "ant.fill",
                    symbolColorHex: "#EF4444",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#991B1B",
                    badgeOpacity: 0.20
                ),
                IconDesign(
                    name: "API & Microservices",
                    folderStyle: .neon,
                    primaryColorHex: "#8B5CF6",
                    secondaryColorHex: "#EC4899",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "network",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                )
            ]
        ),
        
        // 3. Minimal Workspace
        IconCollection(
            id: "minimal_workspace",
            name: "Minimal Workspace",
            description: "Restrained, monochromatic and calm aesthetics for clean desk minimalists.",
            accentColorHex: "#64748B",
            iconName: "briefcase.fill",
            badge: "CLEAN 📁",
            isFeatured: false,
            categoryTag: "Minimalist",
            author: "FolderStudio Official",
            priceText: "Free",
            designs: [
                IconDesign(
                    name: "Documents Clean",
                    folderStyle: .minimal,
                    primaryColorHex: "#475569",
                    secondaryColorHex: "#334155",
                    isGradient: false,
                    overlayType: .symbol,
                    symbolName: "doc.text.fill",
                    symbolColorHex: "#F8FAFC",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Deep Archive",
                    folderStyle: .minimal,
                    primaryColorHex: "#334155",
                    secondaryColorHex: "#1E293B",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "archivebox.fill",
                    symbolColorHex: "#E2E8F0",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Quick Notes",
                    folderStyle: .minimal,
                    primaryColorHex: "#E2E8F0",
                    secondaryColorHex: "#CBD5E1",
                    isGradient: false,
                    overlayType: .symbol,
                    symbolName: "pencil.and.outline",
                    symbolColorHex: "#1E293B",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Checklist Project",
                    folderStyle: .minimal,
                    primaryColorHex: "#64748B",
                    secondaryColorHex: "#475569",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "checklist",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Inbox Staging",
                    folderStyle: .minimal,
                    primaryColorHex: "#94A3B8",
                    secondaryColorHex: "#64748B",
                    isGradient: false,
                    overlayType: .symbol,
                    symbolName: "tray.full.fill",
                    symbolColorHex: "#0F172A",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Secure Vault",
                    folderStyle: .dark,
                    primaryColorHex: "#1E293B",
                    secondaryColorHex: "#0F172A",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "lock.fill",
                    symbolColorHex: "#F1F5F9",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .squircle,
                    badgeColorHex: "#000000",
                    badgeOpacity: 0.35
                ),
                IconDesign(
                    name: "Starred Priority",
                    folderStyle: .minimal,
                    primaryColorHex: "#D97706",
                    secondaryColorHex: "#B45309",
                    isGradient: false,
                    overlayType: .symbol,
                    symbolName: "star.fill",
                    symbolColorHex: "#FEF3C7",
                    symbolScale: 0.54,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Planning Schedule",
                    folderStyle: .minimal,
                    primaryColorHex: "#2563EB",
                    secondaryColorHex: "#1D4ED8",
                    isGradient: false,
                    overlayType: .symbol,
                    symbolName: "calendar",
                    symbolColorHex: "#EFF6FF",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                )
            ]
        ),
        
        // 4. Dark Mode / Obsidian
        IconCollection(
            id: "dark_mode",
            name: "Dark Mode",
            description: "Moody, high-contrast dark tones with refined glowing details.",
            accentColorHex: "#8B5CF6",
            iconName: "moon.fill",
            badge: "STEALTH 🌑",
            isFeatured: false,
            categoryTag: "Minimalist",
            author: "FolderStudio Official",
            priceText: "Free",
            designs: [
                IconDesign(
                    name: "Stealth Obsidian",
                    folderStyle: .dark,
                    primaryColorHex: "#090D16",
                    secondaryColorHex: "#1E293B",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "shield.fill",
                    symbolColorHex: "#94A3B8",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Cyber Violet",
                    folderStyle: .dark,
                    primaryColorHex: "#180D2B",
                    secondaryColorHex: "#2E1065",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "bolt.fill",
                    symbolColorHex: "#C084FC",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#7E22CE",
                    badgeOpacity: 0.30
                ),
                IconDesign(
                    name: "Midnight Blue",
                    folderStyle: .dark,
                    primaryColorHex: "#0B1528",
                    secondaryColorHex: "#172554",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "waveform",
                    symbolColorHex: "#38BDF8",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Charcoal Slate",
                    folderStyle: .dark,
                    primaryColorHex: "#1C1917",
                    secondaryColorHex: "#292524",
                    isGradient: false,
                    overlayType: .symbol,
                    symbolName: "command",
                    symbolColorHex: "#A8A29E",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Neon Amber",
                    folderStyle: .dark,
                    primaryColorHex: "#1A1305",
                    secondaryColorHex: "#2E2003",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "flame.fill",
                    symbolColorHex: "#F59E0B",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#D97706",
                    badgeOpacity: 0.30
                ),
                IconDesign(
                    name: "Emerald Matrix",
                    folderStyle: .dark,
                    primaryColorHex: "#022C22",
                    secondaryColorHex: "#064E3B",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "cpu.fill",
                    symbolColorHex: "#34D399",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Crimson Eclipse",
                    folderStyle: .dark,
                    primaryColorHex: "#2A080C",
                    secondaryColorHex: "#4C0519",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "sparkles",
                    symbolColorHex: "#FB7185",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .diamond,
                    badgeColorHex: "#E11D48",
                    badgeOpacity: 0.30
                ),
                IconDesign(
                    name: "Deep Space",
                    folderStyle: .dark,
                    primaryColorHex: "#070B19",
                    secondaryColorHex: "#1E1B4B",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "moon.stars.fill",
                    symbolColorHex: "#818CF8",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                )
            ]
        ),
        
        // 5. Creative Studio
        IconCollection(
            id: "creative_studio",
            name: "Creative Studio",
            description: "Expressive palettes for design, video, photography, and sound assets.",
            accentColorHex: "#EC4899",
            iconName: "sparkles",
            designs: [
                IconDesign(
                    name: "Art & Design",
                    folderStyle: .glass,
                    primaryColorHex: "#EC4899",
                    secondaryColorHex: "#8B5CF6",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "paintpalette.fill",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#000000",
                    badgeOpacity: 0.20
                ),
                IconDesign(
                    name: "Photography",
                    folderStyle: .minimal,
                    primaryColorHex: "#0284C7",
                    secondaryColorHex: "#0EA5E9",
                    isGradient: false,
                    overlayType: .symbol,
                    symbolName: "camera.fill",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Audio & Beats",
                    folderStyle: .neon,
                    primaryColorHex: "#7C3AED",
                    secondaryColorHex: "#DB2777",
                    isGradient: true,
                    gradientDirection: .horizontal,
                    overlayType: .symbol,
                    symbolName: "music.note",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .squircle,
                    badgeColorHex: "#5B21B6",
                    badgeOpacity: 0.30
                ),
                IconDesign(
                    name: "Cinema & Video",
                    folderStyle: .dark,
                    primaryColorHex: "#831843",
                    secondaryColorHex: "#4C0519",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "film.fill",
                    symbolColorHex: "#F472B6",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Animation 3D",
                    folderStyle: .neon,
                    primaryColorHex: "#06B6D4",
                    secondaryColorHex: "#3B82F6",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "wand.and.stars",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Typography",
                    folderStyle: .minimal,
                    primaryColorHex: "#EA580C",
                    secondaryColorHex: "#C2410C",
                    isGradient: false,
                    overlayType: .symbol,
                    symbolName: "textformat",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Podcast Mic",
                    folderStyle: .glass,
                    primaryColorHex: "#10B981",
                    secondaryColorHex: "#06B6D4",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "mic.fill",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Asset Library",
                    folderStyle: .classic,
                    primaryColorHex: "#6366F1",
                    secondaryColorHex: "#4F46E5",
                    isGradient: false,
                    overlayType: .symbol,
                    symbolName: "photo.fill",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                )
            ]
        ),
        
        // 6. Nature & Botanicals
        IconCollection(
            id: "nature",
            name: "Nature",
            description: "Earth, ocean, foliage and seasonal inspiration from the wild.",
            accentColorHex: "#10B981",
            iconName: "leaf.fill",
            designs: [
                IconDesign(
                    name: "Evergreen",
                    folderStyle: .minimal,
                    primaryColorHex: "#059669",
                    secondaryColorHex: "#047857",
                    isGradient: false,
                    overlayType: .symbol,
                    symbolName: "leaf.fill",
                    symbolColorHex: "#D1FAE5",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Ocean Depths",
                    folderStyle: .glass,
                    primaryColorHex: "#0369A1",
                    secondaryColorHex: "#0284C7",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "water.waves",
                    symbolColorHex: "#E0F2FE",
                    symbolScale: 0.54,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Sunburst",
                    folderStyle: .softPastel,
                    primaryColorHex: "#EAB308",
                    secondaryColorHex: "#FDE047",
                    isGradient: true,
                    gradientDirection: .radial,
                    overlayType: .symbol,
                    symbolName: "sun.max.fill",
                    symbolColorHex: "#713F12",
                    symbolScale: 0.54,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Mountain Peak",
                    folderStyle: .minimal,
                    primaryColorHex: "#475569",
                    secondaryColorHex: "#334155",
                    isGradient: false,
                    overlayType: .symbol,
                    symbolName: "mountain.2.fill",
                    symbolColorHex: "#F8FAFC",
                    symbolScale: 0.54,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Autumn Blossom",
                    folderStyle: .classic,
                    primaryColorHex: "#EA580C",
                    secondaryColorHex: "#C2410C",
                    isGradient: false,
                    overlayType: .symbol,
                    symbolName: "tree.fill",
                    symbolColorHex: "#FFEDD5",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Camp & Trail",
                    folderStyle: .dark,
                    primaryColorHex: "#14532D",
                    secondaryColorHex: "#052E16",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "tent.fill",
                    symbolColorHex: "#86EFAC",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#166534",
                    badgeOpacity: 0.35
                ),
                IconDesign(
                    name: "Raindrop Lake",
                    folderStyle: .glass,
                    primaryColorHex: "#0EA5E9",
                    secondaryColorHex: "#38BDF8",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "drop.fill",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.48,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Campfire Warmth",
                    folderStyle: .neon,
                    primaryColorHex: "#EA580C",
                    secondaryColorHex: "#E11D48",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "flame.fill",
                    symbolColorHex: "#FEF08A",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                )
            ]
        ),
        
        // 7. Personal Organization
        IconCollection(
            id: "personal_organization",
            name: "Personal Organization",
            description: "Keep family, travel, finance, health, and home files instantly recognizable.",
            accentColorHex: "#F59E0B",
            iconName: "house.fill",
            designs: [
                IconDesign(
                    name: "Home & Family",
                    folderStyle: .softPastel,
                    primaryColorHex: "#F472B6",
                    secondaryColorHex: "#FB7185",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "house.fill",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Finances & Taxes",
                    folderStyle: .classic,
                    primaryColorHex: "#059669",
                    secondaryColorHex: "#047857",
                    isGradient: false,
                    overlayType: .symbol,
                    symbolName: "banknote.fill",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .squircle,
                    badgeColorHex: "#064E3B",
                    badgeOpacity: 0.25
                ),
                IconDesign(
                    name: "World Travel",
                    folderStyle: .glass,
                    primaryColorHex: "#0284C7",
                    secondaryColorHex: "#38BDF8",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "airplane",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#0369A1",
                    badgeOpacity: 0.30
                ),
                IconDesign(
                    name: "Health & Wellness",
                    folderStyle: .softPastel,
                    primaryColorHex: "#FB7185",
                    secondaryColorHex: "#FDA4AF",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "heart.fill",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Education & Courses",
                    folderStyle: .minimal,
                    primaryColorHex: "#7C3AED",
                    secondaryColorHex: "#6D28D9",
                    isGradient: false,
                    overlayType: .symbol,
                    symbolName: "book.fill",
                    symbolColorHex: "#EDE9FE",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Gaming & Fun",
                    folderStyle: .neon,
                    primaryColorHex: "#8B5CF6",
                    secondaryColorHex: "#EC4899",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "gamecontroller.fill",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Automotive",
                    folderStyle: .dark,
                    primaryColorHex: "#1E293B",
                    secondaryColorHex: "#0F172A",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "car.fill",
                    symbolColorHex: "#38BDF8",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Legal & Identity",
                    folderStyle: .minimal,
                    primaryColorHex: "#1E3A8A",
                    secondaryColorHex: "#172554",
                    isGradient: false,
                    overlayType: .symbol,
                    symbolName: "signature",
                    symbolColorHex: "#DBEAFE",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .shield,
                    badgeColorHex: "#1E40AF",
                    badgeOpacity: 0.30
                )
            ]
        ),
        
        // 8. Emoji Express
        IconCollection(
            id: "emoji_express",
            name: "Emoji Express",
            description: "Vibrant, expressive emoji folders for your everyday projects, moods, and hobbies.",
            accentColorHex: "#F59E0B",
            iconName: "face.smiling.inverse",
            badge: "POPULAR ⭐",
            isFeatured: true,
            categoryTag: "Emoji & Fun",
            author: "FolderStudio Official",
            priceText: "Free",
            designs: [
                IconDesign(
                    name: "Rocket Launch",
                    folderStyle: .minimal,
                    primaryColorHex: "#312E81",
                    secondaryColorHex: "#4338CA",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .emoji,
                    symbolScale: 0.55,
                    symbolOffsetY: 0.0,
                    customText: "🚀",
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Hot Projects",
                    folderStyle: .minimal,
                    primaryColorHex: "#DC2626",
                    secondaryColorHex: "#EA580C",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .emoji,
                    symbolScale: 0.55,
                    symbolOffsetY: 0.0,
                    customText: "🔥",
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Creative Spark",
                    folderStyle: .softPastel,
                    primaryColorHex: "#7C3AED",
                    secondaryColorHex: "#DB2777",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .emoji,
                    symbolScale: 0.55,
                    symbolOffsetY: 0.0,
                    customText: "🎨",
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Gaming Hub",
                    folderStyle: .dark,
                    primaryColorHex: "#111827",
                    secondaryColorHex: "#1E1B4B",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .emoji,
                    symbolScale: 0.55,
                    symbolOffsetY: 0.0,
                    customText: "🎮",
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Brainstorm",
                    folderStyle: .classic,
                    primaryColorHex: "#F59E0B",
                    secondaryColorHex: "#D97706",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .emoji,
                    symbolScale: 0.55,
                    symbolOffsetY: 0.0,
                    customText: "💡",
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Wealth & Finance",
                    folderStyle: .classic,
                    primaryColorHex: "#059669",
                    secondaryColorHex: "#047857",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .emoji,
                    symbolScale: 0.55,
                    symbolOffsetY: 0.0,
                    customText: "💸",
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Cinema & Shows",
                    folderStyle: .dark,
                    primaryColorHex: "#7F1D1D",
                    secondaryColorHex: "#991B1B",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .emoji,
                    symbolScale: 0.55,
                    symbolOffsetY: 0.0,
                    customText: "🍿",
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Coffee & Notes",
                    folderStyle: .classic,
                    primaryColorHex: "#78350F",
                    secondaryColorHex: "#451A03",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .emoji,
                    symbolScale: 0.55,
                    symbolOffsetY: 0.0,
                    customText: "☕️",
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Photos & Snaps",
                    folderStyle: .minimal,
                    primaryColorHex: "#0284C7",
                    secondaryColorHex: "#0369A1",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .emoji,
                    symbolScale: 0.55,
                    symbolOffsetY: 0.0,
                    customText: "📸",
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Holiday & Travel",
                    folderStyle: .minimal,
                    primaryColorHex: "#06B6D4",
                    secondaryColorHex: "#0284C7",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .emoji,
                    symbolScale: 0.55,
                    symbolOffsetY: 0.0,
                    customText: "🏝️",
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Pizza & Food",
                    folderStyle: .minimal,
                    primaryColorHex: "#EA580C",
                    secondaryColorHex: "#C2410C",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .emoji,
                    symbolScale: 0.55,
                    symbolOffsetY: 0.0,
                    customText: "🍕",
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Cyber Invader",
                    folderStyle: .dark,
                    primaryColorHex: "#18181B",
                    secondaryColorHex: "#27272A",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .emoji,
                    symbolScale: 0.55,
                    symbolOffsetY: 0.0,
                    customText: "👾",
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Top Secret",
                    folderStyle: .dark,
                    primaryColorHex: "#334155",
                    secondaryColorHex: "#1E293B",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .emoji,
                    symbolScale: 0.55,
                    symbolOffsetY: 0.0,
                    customText: "🔒",
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Favorites",
                    folderStyle: .classic,
                    primaryColorHex: "#CA8A04",
                    secondaryColorHex: "#A16207",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .emoji,
                    symbolScale: 0.55,
                    symbolOffsetY: 0.0,
                    customText: "⭐",
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Cat Lounge",
                    folderStyle: .softPastel,
                    primaryColorHex: "#FB923C",
                    secondaryColorHex: "#FDBA74",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .emoji,
                    symbolScale: 0.55,
                    symbolOffsetY: 0.0,
                    customText: "🐱",
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Music & Audio",
                    folderStyle: .minimal,
                    primaryColorHex: "#6366F1",
                    secondaryColorHex: "#8B5CF6",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .emoji,
                    symbolScale: 0.55,
                    symbolOffsetY: 0.0,
                    customText: "🎧",
                    badgeShape: .none
                )
            ]
        ),
        
        // 9. Pokémon Champions
        IconCollection(
            id: "pokemon_champions",
            name: "Pokémon Champions",
            description: "Iconic pocket monster companions with authentic elemental colors, badges, and custom Poké Ball folder icons.",
            accentColorHex: "#EAB308",
            iconName: "circle.circle.fill",
            badge: "HOT 🔥",
            isFeatured: true,
            categoryTag: "Gaming & Anime",
            author: "FolderStudio Official",
            priceText: "Free",
            designs: [
                IconDesign(
                    name: "Squirtle Face",
                    folderStyle: .classic,
                    primaryColorHex: "#77C8D5",
                    secondaryColorHex: "#3BA4BC",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "drop.fill",
                    symbolColorHex: "#E0F2FE",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    customText: "Squirtle",
                    badgeShape: .none,
                    bundledImageName: "squirtle_folder"
                ),
                IconDesign(
                    name: "Charmander Face",
                    folderStyle: .classic,
                    primaryColorHex: "#F1823D",
                    secondaryColorHex: "#D95D1E",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "flame.fill",
                    symbolColorHex: "#FEF08A",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    customText: "Charmander",
                    badgeShape: .none,
                    bundledImageName: "charmander_folder"
                ),
                IconDesign(
                    name: "Snorlax Face",
                    folderStyle: .classic,
                    primaryColorHex: "#2B5867",
                    secondaryColorHex: "#1E3D48",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "bed.double.fill",
                    symbolColorHex: "#EED7A1",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    customText: "Snorlax",
                    badgeShape: .none,
                    bundledImageName: "snorlax_folder"
                ),
                IconDesign(
                    name: "Meowth Face",
                    folderStyle: .classic,
                    primaryColorHex: "#ECE1B8",
                    secondaryColorHex: "#D4C597",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "dollarsign.circle.fill",
                    symbolColorHex: "#B89B5F",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    customText: "Meowth",
                    badgeShape: .none,
                    bundledImageName: "meowth_folder"
                ),
                IconDesign(
                    name: "Slowpoke Face",
                    folderStyle: .classic,
                    primaryColorHex: "#F3A3B5",
                    secondaryColorHex: "#DE8498",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "waveform.path",
                    symbolColorHex: "#FFF1F2",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    customText: "Slowpoke",
                    badgeShape: .none,
                    bundledImageName: "slowpoke_folder"
                ),
                IconDesign(
                    name: "Poké Ball Folder",
                    folderStyle: .classic,
                    primaryColorHex: "#C02528",
                    secondaryColorHex: "#9B1A1D",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "circle.circle.fill",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    customText: "Poké Ball",
                    badgeShape: .none,
                    bundledImageName: "pokeball_folder"
                ),
                IconDesign(
                    name: "Great Ball Folder",
                    folderStyle: .classic,
                    primaryColorHex: "#0D6EAC",
                    secondaryColorHex: "#095383",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "circle.circle.fill",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    customText: "Great Ball",
                    badgeShape: .none,
                    bundledImageName: "greatball_folder"
                ),
                IconDesign(
                    name: "Ultra Ball Folder",
                    folderStyle: .dark,
                    primaryColorHex: "#2D2D2D",
                    secondaryColorHex: "#F2B831",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "circle.circle.fill",
                    symbolColorHex: "#F2B831",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    customText: "Ultra Ball",
                    badgeShape: .none,
                    bundledImageName: "ultraball_folder"
                ),
                IconDesign(
                    name: "Master Ball Folder",
                    folderStyle: .dark,
                    primaryColorHex: "#4C2F63",
                    secondaryColorHex: "#341E45",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "circle.circle.fill",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    customText: "Master Ball",
                    badgeShape: .none,
                    bundledImageName: "masterball_folder"
                ),
                IconDesign(
                    name: "Net Ball Folder",
                    folderStyle: .classic,
                    primaryColorHex: "#007F9E",
                    secondaryColorHex: "#005F77",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "circle.circle.fill",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    customText: "Net Ball",
                    badgeShape: .none,
                    bundledImageName: "netball_folder"
                ),
                IconDesign(
                    name: "Pikachu (Electric)",
                    folderStyle: .classic,
                    primaryColorHex: "#FFDE00",
                    secondaryColorHex: "#F59E0B",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "bolt.fill",
                    symbolColorHex: "#78350F",
                    symbolScale: 0.54,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#EF4444",
                    badgeOpacity: 0.40,
                    badgeScale: 0.72
                ),
                IconDesign(
                    name: "Pokéball Classic",
                    folderStyle: .minimal,
                    primaryColorHex: "#DC2626",
                    secondaryColorHex: "#B91C1C",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "circle.circle.fill",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.54,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#000000",
                    badgeOpacity: 0.35,
                    badgeScale: 0.70
                ),
                IconDesign(
                    name: "Charmander (Fire)",
                    folderStyle: .classic,
                    primaryColorHex: "#EA580C",
                    secondaryColorHex: "#C2410C",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "flame.fill",
                    symbolColorHex: "#FEF08A",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#7C2D12",
                    badgeOpacity: 0.35,
                    badgeScale: 0.70
                ),
                IconDesign(
                    name: "Squirtle (Water)",
                    folderStyle: .classic,
                    primaryColorHex: "#0284C7",
                    secondaryColorHex: "#0369A1",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "drop.fill",
                    symbolColorHex: "#E0F2FE",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#0C4A6E",
                    badgeOpacity: 0.35,
                    badgeScale: 0.70
                ),
                IconDesign(
                    name: "Bulbasaur (Grass)",
                    folderStyle: .classic,
                    primaryColorHex: "#059669",
                    secondaryColorHex: "#047857",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "leaf.fill",
                    symbolColorHex: "#D1FAE5",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#064E3B",
                    badgeOpacity: 0.35,
                    badgeScale: 0.70
                ),
                IconDesign(
                    name: "Gengar (Shadow Ghost)",
                    folderStyle: .dark,
                    primaryColorHex: "#581C87",
                    secondaryColorHex: "#3B0764",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "moon.stars.fill",
                    symbolColorHex: "#F3E8FF",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#2E1065",
                    badgeOpacity: 0.45,
                    badgeScale: 0.70
                ),
                IconDesign(
                    name: "Mew (Psychic Myth)",
                    folderStyle: .softPastel,
                    primaryColorHex: "#F472B6",
                    secondaryColorHex: "#EC4899",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "sparkles",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#831843",
                    badgeOpacity: 0.25,
                    badgeScale: 0.70
                ),
                IconDesign(
                    name: "Snorlax (Rest & Sleep)",
                    folderStyle: .classic,
                    primaryColorHex: "#0F766E",
                    secondaryColorHex: "#115E59",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "bed.double.fill",
                    symbolColorHex: "#FEF3C7",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .roundedRect,
                    badgeColorHex: "#134E4A",
                    badgeOpacity: 0.35,
                    badgeScale: 0.72
                ),
                IconDesign(
                    name: "Charizard (Dragon Flame)",
                    folderStyle: .minimal,
                    primaryColorHex: "#B91C1C",
                    secondaryColorHex: "#7F1D1D",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "flame.fill",
                    symbolColorHex: "#FBBF24",
                    symbolScale: 0.54,
                    symbolOffsetY: 0.0,
                    badgeShape: .shield,
                    badgeColorHex: "#450A0A",
                    badgeOpacity: 0.40,
                    badgeScale: 0.72
                ),
                IconDesign(
                    name: "Blastoise (Hydro Cannon)",
                    folderStyle: .classic,
                    primaryColorHex: "#1D4ED8",
                    secondaryColorHex: "#1E3A8A",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "water.waves",
                    symbolColorHex: "#67E8F9",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .shield,
                    badgeColorHex: "#172554",
                    badgeOpacity: 0.35,
                    badgeScale: 0.72
                ),
                IconDesign(
                    name: "Eevee (Evolution)",
                    folderStyle: .classic,
                    primaryColorHex: "#9A3412",
                    secondaryColorHex: "#7C2D12",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "pawprint.fill",
                    symbolColorHex: "#FEF08A",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#431407",
                    badgeOpacity: 0.35,
                    badgeScale: 0.70
                ),
                IconDesign(
                    name: "Mewtwo (Genetic Legend)",
                    folderStyle: .dark,
                    primaryColorHex: "#6B21A8",
                    secondaryColorHex: "#4C1D95",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "atom",
                    symbolColorHex: "#E9D5FF",
                    symbolScale: 0.54,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#3B0764",
                    badgeOpacity: 0.45,
                    badgeScale: 0.72
                ),
                IconDesign(
                    name: "Ultra Ball",
                    folderStyle: .dark,
                    primaryColorHex: "#18181B",
                    secondaryColorHex: "#27272A",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "circle.circle.fill",
                    symbolColorHex: "#EAB308",
                    symbolScale: 0.54,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#000000",
                    badgeOpacity: 0.50,
                    badgeScale: 0.72
                ),
                IconDesign(
                    name: "Master Ball",
                    folderStyle: .neon,
                    primaryColorHex: "#7E22CE",
                    secondaryColorHex: "#DB2777",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "m.circle.fill",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.54,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#4C1D95",
                    badgeOpacity: 0.40,
                    badgeScale: 0.72
                ),
                IconDesign(
                    name: "Rayquaza (Sky Emerald)",
                    folderStyle: .classic,
                    primaryColorHex: "#047857",
                    secondaryColorHex: "#065F46",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "wind",
                    symbolColorHex: "#FBBF24",
                    symbolScale: 0.54,
                    symbolOffsetY: 0.0,
                    badgeShape: .shield,
                    badgeColorHex: "#022C22",
                    badgeOpacity: 0.40,
                    badgeScale: 0.72
                ),
                IconDesign(
                    name: "Umbreon (Moonlight)",
                    folderStyle: .dark,
                    primaryColorHex: "#09090B",
                    secondaryColorHex: "#18181B",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "moon.fill",
                    symbolColorHex: "#FACC15",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#000000",
                    badgeOpacity: 0.50,
                    badgeScale: 0.70
                )
            ]
        ),
        
        // 10. Retro Arcade & 8-Bit
        IconCollection(
            id: "retro_arcade",
            name: "Retro Arcade & 8-Bit",
            description: "Nostalgic pixel aesthetics, arcade classics, and synthwave gaming vaults.",
            accentColorHex: "#A855F7",
            iconName: "gamecontroller.fill",
            badge: "RETRO 👾",
            isFeatured: true,
            categoryTag: "Gaming & Anime",
            author: "FolderStudio Official",
            priceText: "Free",
            designs: [
                IconDesign(
                    name: "Arcade 1984",
                    folderStyle: .neon,
                    primaryColorHex: "#D946EF",
                    secondaryColorHex: "#06B6D4",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "gamecontroller.fill",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .squircle,
                    badgeColorHex: "#4A044E",
                    badgeOpacity: 0.40,
                    badgeScale: 0.70
                ),
                IconDesign(
                    name: "Extra Life Heart",
                    folderStyle: .minimal,
                    primaryColorHex: "#BE123C",
                    secondaryColorHex: "#881337",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "heart.fill",
                    symbolColorHex: "#FDA4AF",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .diamond,
                    badgeColorHex: "#4C0519",
                    badgeOpacity: 0.35,
                    badgeScale: 0.72
                ),
                IconDesign(
                    name: "Space Invader",
                    folderStyle: .dark,
                    primaryColorHex: "#022C22",
                    secondaryColorHex: "#064E3B",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .emoji,
                    symbolScale: 0.55,
                    symbolOffsetY: 0.0,
                    customText: "👾",
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Super Mushroom",
                    folderStyle: .classic,
                    primaryColorHex: "#DC2626",
                    secondaryColorHex: "#991B1B",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .emoji,
                    symbolScale: 0.55,
                    symbolOffsetY: 0.0,
                    customText: "🍄",
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Quest & Lore",
                    folderStyle: .classic,
                    primaryColorHex: "#1E293B",
                    secondaryColorHex: "#0F172A",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "shield.fill",
                    symbolColorHex: "#F1F5F9",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .shield,
                    badgeColorHex: "#020617",
                    badgeOpacity: 0.40,
                    badgeScale: 0.70
                ),
                IconDesign(
                    name: "Retro Cartridge",
                    folderStyle: .dark,
                    primaryColorHex: "#27272A",
                    secondaryColorHex: "#18181B",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "memorychip",
                    symbolColorHex: "#FDE047",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .roundedRect,
                    badgeColorHex: "#09090B",
                    badgeOpacity: 0.45,
                    badgeScale: 0.72
                ),
                IconDesign(
                    name: "Coin & High Score",
                    folderStyle: .classic,
                    primaryColorHex: "#D97706",
                    secondaryColorHex: "#B45309",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "dollarsign.circle.fill",
                    symbolColorHex: "#FEF08A",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#78350F",
                    badgeOpacity: 0.35,
                    badgeScale: 0.70
                ),
                IconDesign(
                    name: "Cyberpunk 2088",
                    folderStyle: .neon,
                    primaryColorHex: "#8B5CF6",
                    secondaryColorHex: "#EC4899",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "bolt.fill",
                    symbolColorHex: "#FACC15",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .diamond,
                    badgeColorHex: "#3B0764",
                    badgeOpacity: 0.40,
                    badgeScale: 0.70
                )
            ]
        ),
        
        // 11. Apple & Tech Universe
        IconCollection(
            id: "tech_universe",
            name: "Apple & Tech Universe",
            description: "High-tech icons for Apple Silicon, Swift, GitHub, AI models, and cloud infrastructure.",
            accentColorHex: "#0EA5E9",
            iconName: "cpu.fill",
            designs: [
                IconDesign(
                    name: "Swift Bird",
                    folderStyle: .classic,
                    primaryColorHex: "#F05138",
                    secondaryColorHex: "#D63820",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "swift",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.54,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#991B1B",
                    badgeOpacity: 0.30,
                    badgeScale: 0.72
                ),
                IconDesign(
                    name: "Apple Silicon",
                    folderStyle: .dark,
                    primaryColorHex: "#1C1C1E",
                    secondaryColorHex: "#2C2C2E",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "cpu",
                    symbolColorHex: "#E5E5EA",
                    symbolScale: 0.54,
                    symbolOffsetY: 0.0,
                    badgeShape: .squircle,
                    badgeColorHex: "#000000",
                    badgeOpacity: 0.50,
                    badgeScale: 0.72
                ),
                IconDesign(
                    name: "Git Branches",
                    folderStyle: .minimal,
                    primaryColorHex: "#F1502F",
                    secondaryColorHex: "#D93B1B",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "arrow.triangle.branch",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "AI & Neural Net",
                    folderStyle: .minimal,
                    primaryColorHex: "#6366F1",
                    secondaryColorHex: "#06B6D4",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "brain.head.profile",
                    symbolColorHex: "#E0F2FE",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .squircle,
                    badgeColorHex: "#1E1B4B",
                    badgeOpacity: 0.35,
                    badgeScale: 0.70
                ),
                IconDesign(
                    name: "Cloud Serverless",
                    folderStyle: .classic,
                    primaryColorHex: "#0284C7",
                    secondaryColorHex: "#0369A1",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "cloud.fill",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Docker Container",
                    folderStyle: .classic,
                    primaryColorHex: "#0DB7ED",
                    secondaryColorHex: "#0284C7",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "shippingbox.fill",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Terminal Hacker",
                    folderStyle: .dark,
                    primaryColorHex: "#022C22",
                    secondaryColorHex: "#064E3B",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "terminal.fill",
                    symbolColorHex: "#4ADE80",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                ),
                IconDesign(
                    name: "Database Cluster",
                    folderStyle: .classic,
                    primaryColorHex: "#336791",
                    secondaryColorHex: "#1E3A8A",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "cylinder.split.1x2.fill",
                    symbolColorHex: "#E0F2FE",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .none
                )
            ]
        ),
        
        // 12. Anime & Manga
        IconCollection(
            id: "anime_manga",
            name: "Anime & Manga",
            description: "Inspired by legendary shonen adventures, ninjas, pirates, and magical anime.",
            accentColorHex: "#FF5722",
            iconName: "flame.circle.fill",
            designs: [
                IconDesign(
                    name: "Straw Hat Voyage",
                    folderStyle: .dark,
                    primaryColorHex: "#0F172A",
                    secondaryColorHex: "#1E293B",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "skull.fill",
                    symbolColorHex: "#FACC15",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#334155",
                    badgeOpacity: 0.40,
                    badgeScale: 0.70
                ),
                IconDesign(
                    name: "Hidden Leaf Shinobi",
                    folderStyle: .minimal,
                    primaryColorHex: "#EA580C",
                    secondaryColorHex: "#9A3412",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "wind",
                    symbolColorHex: "#F1F5F9",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#18181B",
                    badgeOpacity: 0.40,
                    badgeScale: 0.70
                ),
                IconDesign(
                    name: "Dragon Ball Wish",
                    folderStyle: .classic,
                    primaryColorHex: "#EAB308",
                    secondaryColorHex: "#CA8A04",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "star.fill",
                    symbolColorHex: "#DC2626",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#78350F",
                    badgeOpacity: 0.35,
                    badgeScale: 0.70
                ),
                IconDesign(
                    name: "Scout Regiment Wings",
                    folderStyle: .classic,
                    primaryColorHex: "#14532D",
                    secondaryColorHex: "#166534",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "shield.lefthalf.filled",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .shield,
                    badgeColorHex: "#052E16",
                    badgeOpacity: 0.40,
                    badgeScale: 0.72
                ),
                IconDesign(
                    name: "Demon Slayer Nichirin",
                    folderStyle: .classic,
                    primaryColorHex: "#0F766E",
                    secondaryColorHex: "#134E4A",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "water.waves",
                    symbolColorHex: "#FFFFFF",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .squircle,
                    badgeColorHex: "#042F2E",
                    badgeOpacity: 0.40,
                    badgeScale: 0.70
                ),
                IconDesign(
                    name: "Cursed Energy",
                    folderStyle: .dark,
                    primaryColorHex: "#1E1B4B",
                    secondaryColorHex: "#0F172A",
                    isGradient: true,
                    gradientDirection: .diagonal,
                    overlayType: .symbol,
                    symbolName: "eye.fill",
                    symbolColorHex: "#38BDF8",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#111827",
                    badgeOpacity: 0.45,
                    badgeScale: 0.70
                ),
                IconDesign(
                    name: "Super Saiyan Glow",
                    folderStyle: .classic,
                    primaryColorHex: "#F59E0B",
                    secondaryColorHex: "#D97706",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "sun.max.fill",
                    symbolColorHex: "#67E8F9",
                    symbolScale: 0.52,
                    symbolOffsetY: 0.0,
                    badgeShape: .circle,
                    badgeColorHex: "#78350F",
                    badgeOpacity: 0.35,
                    badgeScale: 0.70
                ),
                IconDesign(
                    name: "Death Note Book",
                    folderStyle: .dark,
                    primaryColorHex: "#09090B",
                    secondaryColorHex: "#18181B",
                    isGradient: true,
                    gradientDirection: .topToBottom,
                    overlayType: .symbol,
                    symbolName: "book.closed.fill",
                    symbolColorHex: "#F4F4F5",
                    symbolScale: 0.50,
                    symbolOffsetY: 0.0,
                    badgeShape: .roundedRect,
                    badgeColorHex: "#27272A",
                    badgeOpacity: 0.45,
                    badgeScale: 0.70
                )
            ]
        )
    ]
    
    static var featuredCollections: [IconCollection] {
        let featuredIds = ["pokemon_champions", "emoji_express", "retro_arcade", "developer_essentials"]
        return featuredIds.compactMap { id in
            allCollections.first(where: { $0.id == id })
        }
    }
}
